### ISSUE TITLE
redux-persist/redux-storage

### ISSUE THREAD

**Issue by lucasbento** [DimitriMikadze/node-redux-auth#2]
Are there any reasons to use [this](https://github.com/DimitriMikadze/node-redux-auth/blob/master/client/src/app/index.js#L17) instead of [redux-persist](https://github.com/rt2zz/redux-persist) or [redux-storage](https://github.com/michaelcontento/redux-storage)?

**Comment by DimiMikadze** [comment]
are there any reasons to use those libraries over native localStorage ?

**Comment by sibelius** [comment]
these libs provide more idiomatic redux code

Imagine that after loading the token you also need to check if there are new notifications for this user, or that you need to move to another URL based on the type of user

you would add all this code in this: https://github.com/DimitriMikadze/node-redux-auth/blob/master/client/src/app/index.js#L19

making it a little bit hard to read, and even harder to test

**Comment by lucasbento** [comment]
If you also wish to persist state and exclude a few ones (such as errors, searches, etc), your code can become a little monster.

In other words, it's not easy to scale.

**Comment by DimiMikadze** [comment]
Thanks guys! I'll use them definitely when i'll need them.
