### ISSUE TITLE
Active routes not changing

### ISSUE THREAD

**Issue by agharsallah** [DimitriMikadze/node-redux-auth#4]
when adding a new link to the tab and `activeClassName` to the Link element the style dose'n apply unless I press refresh.
I've added `{pure:false}` to connect but the same problem persists : https://github.com/ReactTraining/react-router/issues/3536

**Comment by DimiMikadze** [comment]
Hey, sorry for late answer. 

I don't know why activeClassName is not working, in my latest project i'm comparing props.location.pathname and based on that toggling active class.

````
  componentWillReceiveProps(nextProps) {
    if (this.props.currentUrl !== nextProps.currentUrl) {
      this.setState({ activeUrl: nextProps.currentUrl });
    }
  }
````

render

````
  <li className={this.state.activeUrl === '/' ? 'Navigation__active' : ''}>
      <Link to="/">Home</Link>
 </li> 
````

let me know, if you still have difficulties with it.
